name: CI

jobs:
  buildx:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ${{ fromJson(ruby_versions.json) }}
        node_version: ${{ fromJson(node-versions.json) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Buildx
        uses: docker/build-push-action@v2
        with:
          push: false
          build-args: |
            RUBY_VERSION=${{ matrix.ruby_version }}
            NODE_VERSION=${{ matrix.node_version }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6
          tags: ${{ matrix.ruby_version }}-${{ matrix.node_version }}-alpine

      - name: Test image
        run: docker run -i ${{ matrix.ruby_version }}-${{ matrix.node_version }}-alpine /bin/sh -c "ruby --version && node --version"
